// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information.

using System.Collections.Immutable;

using FluentAssertions;

using KubeOps.Generator.Generators;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace KubeOps.Generator.Test;

public class EntityDefinitionGeneratorTest
{
    [Theory]
    [InlineData("", """
                    // <auto-generated>
                    // This code was generated by a tool.
                    // Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
                    // </auto-generated>
                    #pragma warning disable CS1591
                    using KubeOps.Abstractions.Builder;
                    using KubeOps.Abstractions.Entities;

                    public static class EntityDefinitions
                    {
                    }
                    """)]
    [InlineData("""
                [KubernetesEntity(Group = "testing.dev", ApiVersion = "v1", Kind = "TestEntity")]
                public class V1TestEntity : IKubernetesObject<V1ObjectMeta>
                {
                }
                """, """
                     // <auto-generated>
                     // This code was generated by a tool.
                     // Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
                     // </auto-generated>
                     #pragma warning disable CS1591
                     using KubeOps.Abstractions.Builder;
                     using KubeOps.Abstractions.Entities;

                     public static class EntityDefinitions
                     {
                         public static readonly EntityMetadata V1TestEntity = new("TestEntity", "v1", "testing.dev", null);
                     }
                     """)]
    [InlineData("""
                [KubernetesEntity(Group = "testing.dev", ApiVersion = "v1", Kind = "TestEntity")]
                public class V1TestEntity : IKubernetesObject<V1ObjectMeta>
                {
                }

                [KubernetesEntity(Group = "testing.dev", ApiVersion = "v1", Kind = "AnotherEntity")]
                public class V1AnotherEntity : IKubernetesObject<V1ObjectMeta>
                {
                }
                """, """
                     // <auto-generated>
                     // This code was generated by a tool.
                     // Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
                     // </auto-generated>
                     #pragma warning disable CS1591
                     using KubeOps.Abstractions.Builder;
                     using KubeOps.Abstractions.Entities;

                     public static class EntityDefinitions
                     {
                         public static readonly EntityMetadata V1TestEntity = new("TestEntity", "v1", "testing.dev", null);
                         public static readonly EntityMetadata V1AnotherEntity = new("AnotherEntity", "v1", "testing.dev", null);
                     }
                     """)]
    public void Should_Generate_Correct_Code(string input, string expectedResult)
    {
        var inputCompilation = input.CreateCompilation();
        expectedResult = expectedResult.ReplaceLineEndings();

        var driver = CSharpGeneratorDriver.Create(new EntityDefinitionGenerator());
        driver.RunGeneratorsAndUpdateCompilation(inputCompilation, out var output, out ImmutableArray<Diagnostic> _);

        var result = output.SyntaxTrees
            .First(s => s.FilePath.Contains("EntityDefinitions.g.cs"))
            .ToString().ReplaceLineEndings();
        result.Should().Be(expectedResult);
    }
}
