using System.Text;

using KubeOps.Generator.EntityDefinitions;

using Microsoft.CodeAnalysis.Text;

namespace KubeOps.Generator.Test;

public class EntityDefinitionGeneratorTest
{
    [Fact]
    public Task Should_Generate_Empty_Definitions() =>
        new GeneratorTest<EntityDefinitionGenerator>
        {
            TestState =
            {
                Sources = { string.Empty },
                GeneratedSources =
                {
                    (typeof(EntityDefinitionGenerator), "EntityDefinitions.g.cs", SourceText.From(
                        "// <auto-generated/>\n\nusing KubeOps.Abstractions.Builder;\nusing KubeOps.Abstractions.Entities;\n\npublic static class EntityDefinitions\n{\n    public static IOperatorBuilder RegisterEntitiyMetadata(this IOperatorBuilder builder)\n    {\n        return builder;\n    }\n}",
                        Encoding.UTF8,
                        SourceHashAlgorithm.Sha256)),
                },
            },
        }.RunAsync();
}
