// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information.

using System.Collections.Immutable;

using FluentAssertions;

using KubeOps.Generator.Generators;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace KubeOps.Generator.Test;

public class FinalizerRegistrationGeneratorTest
{
    [Theory]
    [InlineData("", """
                    // <auto-generated>
                    // This code was generated by a tool.
                    // Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
                    // </auto-generated>
                    #pragma warning disable CS1591
                    using KubeOps.Abstractions.Builder;

                    public static class FinalizerRegistrations
                    {
                        public static IOperatorBuilder RegisterFinalizers(this IOperatorBuilder builder)
                        {
                            return builder;
                        }
                    }
                    """)]
    [InlineData("""
                using k8s;
                using k8s.Models;
                using KubeOps.Abstractions.Finalizer;
                
                [KubernetesEntity(Group = "testing.dev", ApiVersion = "v1", Kind = "TestEntity")]
                public sealed class V1TestEntity : IKubernetesObject<V1ObjectMeta>
                {
                }

                public sealed class V1TestEntityFinalizer : IEntityFinalizer<V1TestEntity>
                {
                }
                """, """
                     // <auto-generated>
                     // This code was generated by a tool.
                     // Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
                     // </auto-generated>
                     #pragma warning disable CS1591
                     using KubeOps.Abstractions.Builder;

                     public static class FinalizerRegistrations
                     {
                         public const string V1TestEntityFinalizerIdentifier = "testing.dev/v1testentityfinalizer";
                         public static IOperatorBuilder RegisterFinalizers(this IOperatorBuilder builder)
                         {
                             builder.AddFinalizer<global::V1TestEntityFinalizer, global::V1TestEntity>(V1TestEntityFinalizerIdentifier);
                             return builder;
                         }
                     }
                     """)]
    [InlineData("""
                using k8s;
                using k8s.Models;
                using KubeOps.Abstractions.Finalizer;

                [KubernetesEntity(Group = "testing.dev", ApiVersion = "v1", Kind = "TestEntity")]
                public sealed class V1TestEntity : IKubernetesObject<V1ObjectMeta>
                {
                }

                public abstract class EntityFinalizerBase<TEntity> : IEntityFinalizer<TEntity> 
                    where TEntity : IKubernetesObject<V1ObjectMeta>
                {
                }
                
                public sealed class V1TestEntityFinalizer : EntityFinalizerBase<V1TestEntity>
                {
                }
                """, """
                     // <auto-generated>
                     // This code was generated by a tool.
                     // Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
                     // </auto-generated>
                     #pragma warning disable CS1591
                     using KubeOps.Abstractions.Builder;

                     public static class FinalizerRegistrations
                     {
                         public const string V1TestEntityFinalizerIdentifier = "testing.dev/v1testentityfinalizer";
                         public static IOperatorBuilder RegisterFinalizers(this IOperatorBuilder builder)
                         {
                             builder.AddFinalizer<global::V1TestEntityFinalizer, global::V1TestEntity>(V1TestEntityFinalizerIdentifier);
                             return builder;
                         }
                     }
                     """)]
    [InlineData("""
                using k8s;
                using k8s.Models;
                using KubeOps.Abstractions.Finalizer;

                [KubernetesEntity(Group = "testing.dev", ApiVersion = "v1", Kind = "TestEntity")]
                public sealed class V1TestEntity : IKubernetesObject<V1ObjectMeta>
                {
                }

                public sealed class V1TestEntityCleanupDeployment : IEntityFinalizer<V1TestEntity>
                {
                }

                public sealed class V1TestEntityCleanupOtherResourcesSuchThatThisFinalizerHasAVeryLongName : IEntityFinalizer<V1TestEntity>
                {
                }
                """, """
                     // <auto-generated>
                     // This code was generated by a tool.
                     // Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
                     // </auto-generated>
                     #pragma warning disable CS1591
                     using KubeOps.Abstractions.Builder;

                     public static class FinalizerRegistrations
                     {
                         public const string V1TestEntityCleanupDeploymentIdentifier = "testing.dev/v1testentitycleanupdeploymentfinalizer";
                         public const string V1TestEntityCleanupOtherResourcesSuchThatThisFinalizerHasAVeryLongNameIdentifier = "testing.dev/v1testentitycleanupotherresourcessuchthatthisfinali";
                         public static IOperatorBuilder RegisterFinalizers(this IOperatorBuilder builder)
                         {
                             builder.AddFinalizer<global::V1TestEntityCleanupDeployment, global::V1TestEntity>(V1TestEntityCleanupDeploymentIdentifier);
                             builder.AddFinalizer<global::V1TestEntityCleanupOtherResourcesSuchThatThisFinalizerHasAVeryLongName, global::V1TestEntity>(V1TestEntityCleanupOtherResourcesSuchThatThisFinalizerHasAVeryLongNameIdentifier);
                             return builder;
                         }
                     }
                     """)]
    [InlineData("""
                using k8s;
                using k8s.Models;
                using KubeOps.Abstractions.Finalizer;

                [KubernetesEntity(Group = "testing.dev", ApiVersion = "v1", Kind = "TestEntity")]
                public sealed class V1TestEntity : IKubernetesObject<V1ObjectMeta>
                {
                }

                public abstract class EntityFinalizerBase<TEntity> : IEntityFinalizer<TEntity> 
                    where TEntity : IKubernetesObject<V1ObjectMeta>
                {
                }
                
                public sealed class V1TestEntityFinalizer : EntityFinalizerBase<V1TestEntity>
                {
                }

                public sealed class V1TestEntityFinalizer2 : IEntityFinalizer<V1TestEntity>
                {
                }
                """, """
                     // <auto-generated>
                     // This code was generated by a tool.
                     // Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
                     // </auto-generated>
                     #pragma warning disable CS1591
                     using KubeOps.Abstractions.Builder;

                     public static class FinalizerRegistrations
                     {
                         public const string V1TestEntityFinalizerIdentifier = "testing.dev/v1testentityfinalizer";
                         public const string V1TestEntityFinalizer2Identifier = "testing.dev/v1testentityfinalizer2finalizer";
                         public static IOperatorBuilder RegisterFinalizers(this IOperatorBuilder builder)
                         {
                             builder.AddFinalizer<global::V1TestEntityFinalizer, global::V1TestEntity>(V1TestEntityFinalizerIdentifier);
                             builder.AddFinalizer<global::V1TestEntityFinalizer2, global::V1TestEntity>(V1TestEntityFinalizer2Identifier);
                             return builder;
                         }
                     }
                     """)]
    public void Should_Generate_Correct_Code(string input, string expectedResult)
    {
        var inputCompilation = input.CreateCompilation();
        expectedResult = expectedResult.ReplaceLineEndings();

        var driver = CSharpGeneratorDriver.Create(new FinalizerRegistrationGenerator());
        driver.RunGeneratorsAndUpdateCompilation(inputCompilation, out var output, out ImmutableArray<Diagnostic> _);

        var result = output.SyntaxTrees
            .First(s => s.FilePath.Contains("FinalizerRegistrations.g.cs"))
            .ToString().ReplaceLineEndings();
        result.Should().Be(expectedResult);
    }
}
