using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace KubeOps.Generator.Generators;

public static class AutoGeneratedSyntaxTrivia
{
    public static readonly SyntaxTrivia Instance =
        SyntaxFactory.Comment(
            """
            // <auto-generated>
            // This code was generated by a tool.
            // Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
            // </auto-generated>
            """);
}
