// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information.

using System.Text;

using KubeOps.Generator.SyntaxReceiver;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace KubeOps.Generator.Generators;

[Generator]
internal class EntityDefinitionGenerator : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context)
    {
        context.RegisterForSyntaxNotifications(() => new KubernetesEntitySyntaxReceiver());
    }

    public void Execute(GeneratorExecutionContext context)
    {
        if (context.SyntaxContextReceiver is not KubernetesEntitySyntaxReceiver receiver)
        {
            return;
        }

        var declaration = CompilationUnit()
            .WithUsings(
                List(
                    new List<UsingDirectiveSyntax>
                    {
                        UsingDirective(IdentifierName("KubeOps.Abstractions.Builder")),
                        UsingDirective(IdentifierName("KubeOps.Abstractions.Entities")),
                    }))
            .WithLeadingTrivia(AutoGeneratedSyntaxTrivia.Instance)
            .WithMembers(SingletonList<MemberDeclarationSyntax>(ClassDeclaration("EntityDefinitions")
                .WithModifiers(TokenList(
                    Token(SyntaxKind.PublicKeyword), Token(SyntaxKind.StaticKeyword)))
                .WithMembers(
                    List<MemberDeclarationSyntax>(receiver.Entities.Select(e => FieldDeclaration(
                            VariableDeclaration(
                                    IdentifierName("EntityMetadata"))
                                .WithVariables(
                                    SingletonSeparatedList(
                                        VariableDeclarator(e.Class.Identifier)
                                            .WithInitializer(
                                                EqualsValueClause(
                                                    ImplicitObjectCreationExpression()
                                                        .WithArgumentList(
                                                            ArgumentList(
                                                                SeparatedList(new List<ArgumentSyntax>
                                                                {
                                                                    Argument(LiteralExpression(
                                                                        SyntaxKind.StringLiteralExpression,
                                                                        Literal(e.Kind))),
                                                                    Argument(LiteralExpression(
                                                                        SyntaxKind.StringLiteralExpression,
                                                                        Literal(e.Version))),
                                                                    Argument(e.Group switch
                                                                    {
                                                                        null => LiteralExpression(
                                                                            SyntaxKind.NullLiteralExpression),
                                                                        _ => LiteralExpression(
                                                                            SyntaxKind.StringLiteralExpression,
                                                                            Literal(e.Group)),
                                                                    }),
                                                                    Argument(e.Plural switch
                                                                    {
                                                                        null => LiteralExpression(
                                                                            SyntaxKind.NullLiteralExpression),
                                                                        _ => LiteralExpression(
                                                                            SyntaxKind.StringLiteralExpression,
                                                                            Literal(e.Plural)),
                                                                    }),
                                                                }))))))))
                        .WithModifiers(
                            TokenList(
                                Token(SyntaxKind.PublicKeyword),
                                Token(SyntaxKind.StaticKeyword),
                                Token(SyntaxKind.ReadOnlyKeyword))))))))
            .NormalizeWhitespace();

        context.AddSource(
            "EntityDefinitions.g.cs",
            SourceText.From(declaration.ToFullString(), Encoding.UTF8, SourceHashAlgorithm.Sha256));
    }
}
