name: Code Security Testing

on:
  pull_request:
    branches:
      - main
      - release
  schedule:
    - cron: "0 20 * * 5"

concurrency:
  group: security-${{ github.ref }}
  cancel-in-progress: true

jobs:
  codeQL:
    name: Analyze
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: csharp

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x

      - name: Build
        run: dotnet build --configuration Release

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
