name: Code Security Testing

on:
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 20 * * 5"

jobs:
  codeQL:
    name: Analyze
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: ["csharp"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - run: git checkout HEAD^2
        if: ${{ github.event_name == 'pull_request' }}

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.302

      - name: Build
        run: ./build.sh --target compile --no-logo

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
